---

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: restart metabase
  service:
    name: metabase
    state: restarted
  become: yes

- name: remove old versions
  include_tasks: upgrade_cleanup.yml
  when: metabase_upgrade_cleanup
